// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhr2SG67OYKGuIOmnJ8OrWcEs-7HU0V7U',
    appId: '1:576379291163:web:5df70fe61b5bc56ba99abe',
    messagingSenderId: '576379291163',
    projectId: 'i-know-a-spot-11d2b',
    authDomain: 'i-know-a-spot-11d2b.firebaseapp.com',
    storageBucket: 'i-know-a-spot-11d2b.firebasestorage.app',
    measurementId: 'G-4J6RS7WBDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGqUk0AM4c8uG9a8skHrVGy8quJpM5sng',
    appId: '1:576379291163:android:502a94fa395c1467a99abe',
    messagingSenderId: '576379291163',
    projectId: 'i-know-a-spot-11d2b',
    storageBucket: 'i-know-a-spot-11d2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQTAO58v1epDopkOl6jjm3X1TRsu8wiSI',
    appId: '1:576379291163:ios:10a724a46e748050a99abe',
    messagingSenderId: '576379291163',
    projectId: 'i-know-a-spot-11d2b',
    storageBucket: 'i-know-a-spot-11d2b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQTAO58v1epDopkOl6jjm3X1TRsu8wiSI',
    appId: '1:576379291163:ios:10a724a46e748050a99abe',
    messagingSenderId: '576379291163',
    projectId: 'i-know-a-spot-11d2b',
    storageBucket: 'i-know-a-spot-11d2b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhr2SG67OYKGuIOmnJ8OrWcEs-7HU0V7U',
    appId: '1:576379291163:web:e80d0faaa4435dcfa99abe',
    messagingSenderId: '576379291163',
    projectId: 'i-know-a-spot-11d2b',
    authDomain: 'i-know-a-spot-11d2b.firebaseapp.com',
    storageBucket: 'i-know-a-spot-11d2b.firebasestorage.app',
    measurementId: 'G-EBJNJRWHVW',
  );
}
